import type { ControlDef } from '@/lib/types';

// Original Framer control ranges and defaults; the KPI preset overrides appearance.
export const particleControlGroups: { key: string; label: string; controls: ControlDef[] }[] = [
  { key: 'source', label: 'Source', controls: [
    {"key":"source","label":"Source","type":"select","default":"Primitive","options":["Primitive"]},
  ] },
  { key: 'shape', label: 'Shape', controls: [
    {"key":"shape.type","label":"Type","type":"select","default":"MobiusStrip","options":["Cloud","MobiusStrip","TorusKnot","Torus","Sphere","Icosahedron","Box","TrefoilKnot"]},
    {"key":"shape.particleCount","label":"Count","type":"slider","default":10000,"min":500,"max":30000,"step":500},
  ] },
  { key: 'material', label: 'Material', controls: [
    {"key":"material.particleColor","label":"Particle","type":"color","default":"#030303"},
    {"key":"material.transparentBackground","label":"Transparent","type":"toggle","default":"On","options":["On","Off"]},
    {"key":"material.backgroundColor","label":"Background","type":"color","default":"#eeeeee","visibleWhen":{"key":"material.transparentBackground","equals":"Off"}},
    {"key":"material.particleSize","label":"Size","type":"slider","default":0.03,"min":0.005,"max":0.2,"step":0.005},
    {"key":"material.opacity","label":"Opacity","type":"slider","default":1,"min":0,"max":1,"step":0.01},
    {"key":"material.showCursor","label":"Cursor","type":"toggle","default":"On","options":["On","Off"]},
  ] },
  { key: 'layout', label: 'Overflow', controls: [
    {"key":"layout.horizontalOverflowVisible","label":"Horizontal","type":"toggle","default":"On","options":["On","Off"]},
    {"key":"layout.horizontalOverscan","label":"X Overscan","type":"slider","default":300,"min":0,"max":2000,"step":10},
  ] },
  { key: 'transform', label: 'Position', controls: [
    {"key":"transform.x","label":"X","type":"slider","default":0,"min":-30,"max":30,"step":0.1},
    {"key":"transform.y","label":"Y","type":"slider","default":0,"min":-30,"max":30,"step":0.1},
    {"key":"transform.z","label":"Z","type":"slider","default":0,"min":-30,"max":30,"step":0.1},
    {"key":"transform.rotateX","label":"Rotate X","type":"slider","default":0,"min":-360,"max":360,"step":1},
    {"key":"transform.rotateY","label":"Rotate Y","type":"slider","default":0,"min":-360,"max":360,"step":1},
    {"key":"transform.rotateZ","label":"Rotate Z","type":"slider","default":0,"min":-360,"max":360,"step":1},
    {"key":"transform.scale","label":"Scale","type":"slider","default":1,"min":0.1,"max":10,"step":0.05},
  ] },
  { key: 'camera', label: 'Camera', controls: [
    {"key":"camera.x","label":"X","type":"slider","default":0,"min":-40,"max":40,"step":0.5},
    {"key":"camera.y","label":"Y","type":"slider","default":0,"min":-40,"max":40,"step":0.5},
    {"key":"camera.z","label":"Z","type":"slider","default":10,"min":2,"max":60,"step":0.5},
    {"key":"camera.fov","label":"FOV","type":"slider","default":90,"min":20,"max":120,"step":1},
  ] },
  { key: 'fog', label: 'Fog', controls: [
    {"key":"fog.enabled","label":"Enabled","type":"toggle","default":"On","options":["On","Off"]},
    {"key":"fog.color","label":"Color","type":"color","default":"#c1c1c1"},
    {"key":"fog.near","label":"Near","type":"slider","default":8,"min":0,"max":50,"step":0.1},
    {"key":"fog.far","label":"Far","type":"slider","default":22,"min":1,"max":100,"step":0.1},
  ] },
  { key: 'orbit', label: 'Orbit', controls: [
    {"key":"orbit.lockRotation","label":"Lock Rotation","type":"toggle","default":"Off","options":["On","Off"]},
    {"key":"orbit.autoRotate","label":"Auto","type":"toggle","default":"On","options":["On","Off"]},
    {"key":"orbit.autoRotateSpeed","label":"Speed","type":"slider","default":0.9,"min":-5,"max":5,"step":0.1},
    {"key":"orbit.enableZoom","label":"Zoom","type":"toggle","default":"Off","options":["On","Off"]},
    {"key":"orbit.enablePan","label":"Pan","type":"toggle","default":"Off","options":["On","Off"]},
  ] },
  { key: 'interaction', label: 'Interaction', controls: [
    {"key":"interaction.radius","label":"Radius","type":"slider","default":2.2,"min":0,"max":20,"step":0.1},
    {"key":"interaction.strength","label":"Strength","type":"slider","default":0.08,"min":0,"max":2,"step":0.01},
    {"key":"interaction.coreRadius","label":"Core Radius","type":"slider","default":0.55,"min":0,"max":10,"step":0.05},
    {"key":"interaction.coreStrength","label":"Core Force","type":"slider","default":0.22,"min":0,"max":5,"step":0.01},
    {"key":"interaction.falloff","label":"Falloff","type":"slider","default":3,"min":0.5,"max":10,"step":0.1},
  ] },
  { key: 'movement', label: 'Movement', controls: [
    {"key":"movement.speed","label":"Speed","type":"slider","default":0.1,"min":0,"max":1,"step":0.01},
    {"key":"movement.damping","label":"Damping","type":"slider","default":0.78,"min":0,"max":1,"step":0.005},
    {"key":"movement.returnForce","label":"Return","type":"slider","default":0.045,"min":0,"max":0.2,"step":0.001},
    {"key":"movement.maxVelocity","label":"Max Vel","type":"slider","default":0.35,"min":0,"max":10,"step":0.05},
    {"key":"movement.restlessEnabled","label":"Restless","type":"toggle","default":"On","options":["On","Off"]},
    {"key":"movement.restlessValue","label":"Amount","type":"slider","default":0.006,"min":0,"max":0.1,"step":0.001},
  ] },
  { key: 'animation', label: 'Animation', controls: [
    {"key":"animation.enabled","label":"Enabled","type":"toggle","default":"On","options":["On","Off"]},
    {"key":"animation.xAmount","label":"X Amount","type":"slider","default":0.02,"min":0,"max":0.5,"step":0.005},
    {"key":"animation.yAmount","label":"Y Amount","type":"slider","default":0.02,"min":0,"max":0.5,"step":0.005},
    {"key":"animation.zAmount","label":"Z Amount","type":"slider","default":0.02,"min":0,"max":0.5,"step":0.005},
    {"key":"animation.xFrequency","label":"X Freq","type":"slider","default":1.2,"min":0,"max":5,"step":0.1},
    {"key":"animation.yFrequency","label":"Y Freq","type":"slider","default":0.55,"min":0,"max":5,"step":0.1},
    {"key":"animation.zFrequency","label":"Z Freq","type":"slider","default":0.35,"min":0,"max":5,"step":0.1},
  ] },
  { key: 'exportOptions', label: 'Export PNG', controls: [
    {"key":"exportOptions.showButton","label":"Show Button","type":"toggle","default":"On","options":["On","Off"]},
    {"key":"exportOptions.label","label":"Label","type":"text","default":"Export PNG"},
    {"key":"exportOptions.fileName","label":"File Name","type":"text","default":"particles.png"},
    {"key":"exportOptions.scale","label":"Resolution","type":"slider","default":2,"min":1,"max":4,"step":1},
    {"key":"exportOptions.removeFog","label":"Remove Fog","type":"toggle","default":"On","options":["On","Off"]},
    {"key":"exportOptions.position","label":"Position","type":"select","default":"bottom-right","options":["top-left","top-right","bottom-left","bottom-right"]},
    {"key":"exportOptions.offset","label":"Offset","type":"slider","default":16,"min":0,"max":100,"step":1},
    {"key":"exportOptions.paddingX","label":"Padding X","type":"slider","default":16,"min":0,"max":60,"step":1},
    {"key":"exportOptions.paddingY","label":"Padding Y","type":"slider","default":12,"min":0,"max":40,"step":1},
    {"key":"exportOptions.radius","label":"Radius","type":"slider","default":8,"min":0,"max":100,"step":1},
    {"key":"exportOptions.fontSize","label":"Font Size","type":"slider","default":14,"min":8,"max":40,"step":1},
    {"key":"exportOptions.fontWeight","label":"Weight","type":"slider","default":500,"min":100,"max":900,"step":100},
    {"key":"exportOptions.background","label":"Background","type":"color","default":"#111111"},
    {"key":"exportOptions.textColor","label":"Text","type":"color","default":"#FFFFFF"},
    {"key":"exportOptions.showBorder","label":"Border","type":"toggle","default":"Off","options":["On","Off"]},
    {"key":"exportOptions.borderColor","label":"Border Color","type":"color","default":"#FFFFFF33"},
    {"key":"exportOptions.borderWidth","label":"Border Width","type":"slider","default":1,"min":0,"max":10,"step":1},
    {"key":"exportOptions.shadow","label":"Shadow","type":"text","default":"0 8px 24px rgba(0,0,0,0.18)"},
  ] },
];
